import crudStore from "./crud-store";

export var genre = crudStore("GENRE", "GENRES");
export var artist = crudStore("ARTIST", "ARTISTS");
export var track = crudStore("TRACK", "TRACKS");
export var album = crudStore("ALBUM", "ALBUMS");
export var single = crudStore("SINGLE", "SINGLES");
export var chartAlbum = crudStore("CHARTALBUM", "CHARTALBUMS");
export var chartTrack = crudStore("CHARTTRACK", "CHARTTRACKS");
export var newReleaseAlbum= crudStore("NEWRELEASEALBUM", "NEWRELEASALBUMS");
export var newReleaseTrack= crudStore("NEWRELEASETRACK", "NEWRELEASETRACKS");
export var newReleaseSingle= crudStore("NEWRELEASESINGLE", "NEWRELEASESINGLES");
export var country = crudStore("COUNTRY", "COUNTRIES");
export var opportunityType = crudStore("OPPORTUNITYTYPE", "OPPORTUNITYTYPES");
export var opportunityStatus = crudStore("OPPORTUNITYSTATUS", "OPPORTUNITYSTATUSES");
export var opportunityRatePeriod = crudStore("OPPORTUNITYRATEPERIOD", "OPPORTUNITYRATEPERIODS");
export var opportunityAgentRating = crudStore("OPPORTUNITYAGENTRATING", "OPPORTUNITYAGENTRATINGS");
export var opportunityType = crudStore("OPPORTUNITYTYPE", "OPPORTUNITYTYPES");
export var agency= crudStore("AGENCY", "AGENCIES");
export var agent = crudStore("AGENT", "AGENTS");
export var note = crudStore("NOTE", "NOTES");
export var opportunity = crudStore("OPPORTUNITY", "OPPORTUNITIES");
export var profile = crudStore("PROFILE", "PROFILES"); 
export var task = crudStore("TASK", "TASKS"); 
export var email = crudStore("EMAIL", "EMAILS"); 
